env=TEST
test.meta=http://YOUR_META_SERVER:7001
pre.meta=http://YOUR_META_SERVER:7001
prod.meta=http://YOUR_META_SERVER:7001
app.id=deepcover-datacenter
puppeteer.bootstrap.enabled=true
puppeteer.bootstrap.namespaces=application,JSBZ.SOA_PUBLIC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher