spring.data.neo4j.uri = bolt://YOUR_NEO4J_HOST:7687
spring.data.neo4j.password = YOUR_NEO4J_PASSWORD
spring.data.neo4j.username = neo4j
hbase.config.hbase.zookeeper.quorum = YOUR_HBASE_ZOOKEEPER_QUORUM
hbase.config.hbase.client.username = YOUR_HBASE_USERNAME
hbase.config.hbase.client.password = YOUR_HBASE_PASSWORD
hbase.table.auditLog = default:auditLog
hbase.table.trace = default:trace
rocketmq.name-server = YOUR_ROCKETMQ_SERVER:9876
aliyun.log.host = cn-hangzhou.log.aliyuncs.com
aliyun.log.accessId = YOUR_ALIYUN_ACCESS_ID
aliyun.log.accessKey = YOUR_ALIYUN_ACCESS_KEY
aliyun.log.project = YOUR_ALIYUN_LOG_PROJECT
aliyun.log.store = YOUR_ALIYUN_LOG_STORE

rocketmq.producer.group= deepcover_collection_code_info_producer
#????????? ??3000ms
rocketmq.producer.send-message-timeout: 3000
#????4096???????????????? 4096
rocketmq.producer.compress-message-body-threshold: 4096
#???????????128K
rocketmq.producer.max-message-size: 4194304
#????????????
rocketmq.producer.retry-times-when-send-failed: 3
#?????????????????????????broker????
rocketmq.producer.retry-next-server: true
#?????????????
rocketmq.producer.retry-times-when-send-async-failed: 3
#deepcover consumer group
rocketmq.consumer.group.ares = deepcover_collection_code_info
#deepcover consumer topic
rocketmq.consumer.tpoic.ares = deepcover_collection_code_info_topic
#hbase consumer topic
rocketmq.consumer.tpoic.hbase = deepcover_hbase_code_info_topic
node.size=30
mq.close=false
